dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@chainlink-brownie-contracts=smartcontractkit/chainlink-brownie-contracts@0.4.0'
wallets:
  from_key: ${PRIVATE_KEY}